### ISSUE TITLE
create a new example for `intake` enhancements

### ISSUE THREAD

**Issue by ryanSoley** [capitalone/rubicon-ml#107]
**Is your documentation request related to a problem? Please describe**

the `intake` integration is currently only mentioned on the landing page and in the quick look

**Describe the solution you'd like**

once we've developed more features, it should have it's own example in the integrations section

**Comment by shania-m** [comment]
* s3 bucket example, local example

**Comment by ryanSoley** [comment]
will revisit as part of the new intake updates in #441, #442, #444
