### ISSUE TITLE
Logging parameters used in pipeline's fit method

### ISSUE THREAD

**Issue by NaziulTalukder** [capitalone/rubicon-ml#109]
**Is your feature request related to a problem? Please describe**
Rubicon pipeline stores parameters of estimators used inside the pipeline when `fit` method is called. But sometimes we might want to inject some parameter in `fit` method of the pipeline for a specific step. Currently user will need to manually log those parameters. It would be useful to automatically log those parameters. 

**Describe the solution you'd like**
The `fit` method [here](https://github.com/capitalone/rubicon-ml/blob/main/rubicon_ml/sklearn/pipeline.py#L65) could log the `fit_params`  passed in in addition to logging each estimator's parameters. 

**Additional context**
The following code shows an example. When the `fit` method is called from the pipeline the `degree` parameter of `SVC` is logged automatically. But when we are passing in `sample_weight` specifically for `svc` step of the pipeline that parameter is not logged. 

````
import os

import numpy as np
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from rubicon_ml import Rubicon
from rubicon_ml.sklearn import FilterEstimatorLogger, RubiconPipeline


def main():
    root_dir = os.environ.get("EXPERIMENT", "experiment")
    root_path = f"{os.path.dirname(os.getcwd())}/{root_dir}"
    rubicon = Rubicon(persistence="filesystem", root_dir=root_path)
    project = rubicon.get_or_create_project("Sklearn-Pipeline")

    pipeline = RubiconPipeline(
        project,
        [
            ("scaler", StandardScaler()),
            ("svc", SVC()),
        ],
        experiment_kwargs={
            "name": "logged from a RubiconPipeline",
            "model_name": "Rubicon_pipeline",
            "tags": "Rubicon_pipeline",
        },
    )

    X, y = make_classification(random_state=0)
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
    pipeline.fit(X_train, y_train, svc__sample_weight=0.1 * np.ones(len(X_train)))
    print(pipeline.score(X_test, y_test))

    experiment = project.experiments()[0]

    for p in experiment.parameters():
        # printing out a parameter
        if p.name == "svc__degree":
            print("svc degree: ", p.value)
        # Currently this will not be printed and needs to be logged manually
        if p.name == "svc__sample_weight":
            print("svc fit sample weight", p.value)


if __name__ == "__main__":
    main()


````

**Comment by ryanSoley** [comment]
@NaziulTalukder finally got around to adding this in - it won't fully work for the example provided above as numpy arrays are not json serializable, but now it just shows the warning it would normally show instead of erroring. `fit_params` of json serializable types can now be logged
