### ISSUE TITLE
add test for the value error in `project`, `metric`, `experiment` and the other getters 

### ISSUE THREAD

**Issue by andreafehrman** [capitalone/rubicon-ml#142]
**Describe the solution you'd like**
Create a test function so that the value error is correctly thrown in each getter for making sure `name` or `id` is sent as a parameter. 

**Describe alternatives you've considered**
Alternatively, different functions to test this value error in each getter function could be created but it would most likely be more efficient to write one to be used for all.

**Comment by ryanSoley** [comment]
> it would most likely be more efficient to write one to be used for all

I definitely agree - if you wanna take it a step further, you could add something like a `_validate_only_one` helper to the [base client class](https://github.com/capitalone/rubicon-ml/blob/main/rubicon_ml/client/base.py) that contains an abstracted version of this check
> https://github.com/capitalone/rubicon-ml/blob/main/rubicon_ml/client/experiment.py#L97

then you could swap all the duplicates of the lines I just linked with `self._validate_only_one(name=name, id=id)` and write one test for `_validate_one_of`
