### ISSUE TITLE
Update Rubicon Scikit-learn pipelines to support make_pipeline

### ISSUE THREAD

**Issue by shania-m** [capitalone/rubicon-ml#178]
**Is your enhancement request related to a problem? Please describe**
The scikit-learn api supports a method [make_pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.make_pipeline.html) as a wrapper around the `Pipeline` constructor. This shorthand does not require the naming of estimators in the pipeline. I would like the Rubicon Pipeline to support the instantiation of pipelines without the explicit naming of the estimators. The steps assign their names as their types in lowercase automatically.
**Describe the solution you'd like**

This solution would allow user calling make_pipeline without naming the steps like so:
````
anova_pipe = make_pipeline(anova_filter,clf)
anova_pipe.fit(X_train, y_train)
print(anova_pipe)
````

Ouput: 
````
RubiconPipeline(project=<rubicon_ml.client.project.Project object at 0x1a4cb8970>,steps=[('selectkbest', SelectKBest(k=3)), ('linearsvc', LinearSVC())])
````

**Comment by ryanSoley** [comment]
I would add that we should look into providing our user-defined loggers to `make_pipeline` as well. something like
```
anova_pipe = make_pipeline(
    steps=(anova_filter, AnovalLoggerCls), (clf, ClassifierLoggerCls)),
)
```
