### ISSUE TITLE
Artifact Plots in Readable formats

### ISSUE THREAD

**Issue by shania-m** [capitalone/rubicon-ml#191]
**Is your enhancement request related to a problem? Please describe**
In the current implementation, when users artifact plots it is not in a human readable format. A user needs to take additional steps to view the plots. 

**Describe the solution you'd like**
Have artifact plots stored in a readable format like PNGs. This will eliminate the need to take additional steps when sharing plots to be made human readable.

**Comment by ryanSoley** [comment]
this ticket needs a lot more detail but I think it'll end up being a new example in the documentation. I'm gonna move it to the docs milestone for now

we can already log PNGs as artifacts so if they're asking for something else we'll have to figure that out

**Comment by shania-m** [comment]
Our customer's use case requires a collection of plots to be logged with each feature like so:   `{feature_name: png_bytes}`. They use pickle.dumps() for serialization and logging with rubicon. This requires extra effort to structure the dictionaries to make sure that the same concept  (e.g. SHAP feature importance) are logged together . Additionally, extra effort is spent on serializing and unserializing the plots for viewing. 


They are not utilizing the current logging feature for Rubicon since it requires the effort to create a file for the png, then log the file, and finally delete the file. For our customer's optimization they are using in storing the PNGSs memory strings and using the `data_bytes` argument.   If they were to log each as an individual artifact, then they could have 100+ feature importance artifacts as opposed to just one to log and then retrieve.
