### ISSUE TITLE
Specifying Validation Patterns 

### ISSUE THREAD

**Issue by shania-m** [capitalone/rubicon-ml#193]
**Is your enhancement request related to a problem? Please describe**
I would like to have a pattern for specifying validations with Rubicon.

**Describe the solution you'd like**
For example, when validations are tied to subpopulations Rubicon should have a way to specify that validation specifically based on the subpopulation. 

**Describe alternatives you've considered**
This could potentially be solved by having string filtering to the dashboard for visualization.

**Comment by ryanSoley** [comment]
this ticket needs a lot more detail but I think it'll end up being a new example in the documentation. I'm gonna move it to the docs milestone for now

**Comment by ryanSoley** [comment]
won't do for now - can revisit later if this ask comes back up
