### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by martindurant** [capitalone/rubicon-ml#21]
Thank you for making this code public!
It looks like a nice and comprehensive package with a good API. You could hang a lot of functionality onto this. I have not tried to run anything, but here are some thoughts on the current documentation.

- for a new concept like this, the initial leadup showing the scope/purpose is critically important. As far as I understand, really it's about storing machine running parameters and outcomes in a repeatable and searchable way: the set of runs becomes itself data ("AI on AI")
- if possible, I would strongly recommend providing the example notebook as a runnable binder *and* a short video of it in action. To simulate s3, you could use moto-server or minio.
- is there any getting around potential users having to pepper their code with logger statements?
- you may be interested in [intake-sklearn](https://github.com/AlbertDeFusco/intake-sklearn), with which you can expose json serialised sklearn models/artefacts as datasets
- I bet people do some interesting things with the git hooks; this part is a little buried. Note that fsspec has a git backend, you can walk the tree at any branch/tag/hash
- I would love to see some motivation around prefect integration. Will other runners be included? 
- would you recommend Rubicon logging for any non-machine-learning workflow ?
- on behalf of my colleagues, why Dash over holoviz? Is his pluggable?
- why "rubicon" ? :) A name like this should be explained.

**Comment by srilatharanganathan** [comment]
@joe-wolfe21 , lets break this up and address

**Comment by joe-wolfe21** [comment]
#25 addressed most of the quick fix items

remaining items
* if possible, I would strongly recommend providing the example notebook as a runnable binder and a short video of it in action. To simulate s3, you could use moto-server or minio.
* is there any getting around potential users having to pepper their code with logger statements?
* you may be interested in intake-sklearn, with which you can expose json serialised sklearn models/artefacts as datasets
