### ISSUE TITLE
Order matters when removing added tags

### ISSUE THREAD

**Issue by armaan-dhillon** [capitalone/rubicon-ml#294]
**Describe the bug**
Say we add a tag to a Rubicon object after it has been logged using `object.add_tags(["new_tag"])`, we then cannot remove that tag using `object.remove_tags(["old_tag", "new_tag"])` unless the added "new_tag" is first in the removal list.

**Steps/Code to reproduce bug**
```
from rubicon_ml import Rubicon
rubicon = Rubicon(persistence="memory")
project = rubicon.get_or_create_project("Tagging")

experiment = project.log_experiment()
first_parameter = experiment.log_parameter("n_estimators", tags=["tag1", "tag2"])
first_parameter.add_tags(["tag3"])
first_parameter.tags

first_parameter.remove_tags(["tag2", "tag3"])
first_parameter.tags
```
_first_parameter is still tagged with "tag3," but when we do:_
```
from rubicon_ml import Rubicon
rubicon = Rubicon(persistence="memory")
project = rubicon.get_or_create_project("Tagging")

experiment = project.log_experiment()
first_parameter = experiment.log_parameter("n_estimators", tags=["tag1", "tag2"])
first_parameter.add_tags(["tag3"]
first_parameter.tags

first_parameter.remove_tags(["tag3", "tag2"])
first_parameter.tags
```
_We get the desired "tag1" as the only remaining tag on the parameter._

**Expected behavior**
Tags should be properly removed from an object despite the order that they appear in the tags=[] parameter of `remove_tags()`

**Additional context**

**Comment by ryanSoley** [comment]
fixed by #298
