### ISSUE TITLE
Use dictionary for Rubicon resource tagging

### ISSUE THREAD

**Issue by apeterson7** [capitalone/rubicon-ml#402]
**Is your feature request related to a problem? Please describe**
When managing large amounts of Rubicon resources, users need some amount of database-like querying using tags.  
Querying resources would be easier if tagging used a key/value data structure.

**Describe the solution you'd like**
Implement tagging with a dictionary data structure for Rubicon resources (Experiments, Artifacts, etc). 

**Describe alternatives you've considered**
Today, users need to write their own custom code to search through strings. 
For example, an experiment is logged for each round of RFE using the pattern "RFE-iter-{iteration}".  

If we want the second round of RFE, we have to use:
rfe_tag = [tag for tag in experiment.tags if tag.startswith("RFE-iter-")][0]
rfe_tag[9:]

With key/value tags, we could access the rfe iteration with something like:
experiment.tags["rfe_iteration"] 

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by ryanSoley** [comment]
hey @apeterson7! I've got a prototype for something that basically works like this:

```python-console
>>> from rubicon_ml import Rubicon
>>> 
>>> r = Rubicon(persistence="memory")
>>> p = r.create_project(name="name")
>>> e = p.log_experiment(tags=["refit", "best", "iter:0", "parent_id:1234"])
>>> 
>>> e.tags
['refit', 'best', 'iter:0', 'parent_id:1234']
>>> e.tags[0]
'refit'
>>> e.tags[2]
'iter:0'
>>> e.tags["iter"]
'0'
>>> e.tags["parent_id"]
'1234'
>>> e.tags["error"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nvd215/github/capitalone/rubicon-ml/rubicon_ml/client/utils/tags.py", line 16, in __getitem__
    raise KeyError(index_or_key)
KeyError: 'error'
>>> e.tags[5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nvd215/github/capitalone/rubicon-ml/rubicon_ml/client/utils/tags.py", line 18, in __getitem__
    return super().__getitem__(index_or_key)
IndexError: list index out of range
```

would that achieve what you're looking for?
