### ISSUE TITLE
Relax pinned dependencies

### ISSUE THREAD

**Issue by joe-wolfe21** [capitalone/rubicon-ml#67]
**Is your enhancement request related to a problem? Please describe**

It might be wise to take a look at our existing dependencies in [setup.py](https://github.com/capitalone/rubicon/blob/main/setup.py#L11) and see if we can loosen them. We've already had one issue (#65) that spawned from too strict dependencies.

**Describe the solution you'd like**

Take a look and adjust dependency pins (or unpin) as needed

**Comment by ryanSoley** [comment]
closing in favor of edgetest integration #195
> https://github.com/capitalone/edgetest
