### ISSUE TITLE
Generate code snippet to retrieve selected experiment

### ISSUE THREAD

**Issue by joe-wolfe21** [capitalone/rubicon-ml#78]
**Is your feature request related to a problem? Please describe**

Within the dashboard, it's possible to select experiment(s) while exploring the logged data. It could be the case that while exploring, I see an experiment that I'd like to retrieve and fetch more information on using the library. This process could be made easier by adding a "copy code snippet" button directly on the dashboard that gives me exactly what i need to fetch the corresponding experiment

**Describe the solution you'd like**

When an experiment is selected, I'd like to be able to select a button that generates and copies the corresponding code to fetch that experiment using the library

**Comment by ryanSoley** [comment]
done via publishing in #202
