### ISSUE TITLE
Docs link in the readme takes you to a 404 page

### ISSUE THREAD

**Issue by joeGannuscio** [capitalone/rubicon-ml#95]
**Is your documentation request related to a problem? Please describe**
When I click the docs link in the documentation section of the readme, it takes me here (https://capitalone.github.io/rubicon/) and I get a 404 page saying "There isn't a GitHub pages site here". It looks like the link in the readme still points to the old project name instead of rubicon-ml. If I go to (https://capitalone.github.io/rubicon-ml/) I can see the docs as expected.

**Describe the solution you'd like**
The readme docs url updated with the new project name.

**Comment by ryanSoley** [comment]
Thanks for opening the issue! This will be addressed by #93 which will be merged shortly.

**Comment by ryanSoley** [comment]
#93 has been merged - links should be all good!
